const sidePanelList = [
  {
    id: 1,
    list: "Admin",
    iconImg: "images/admin.png",
    dropdownList:"block",
    dropdownList1: "Admin1",
    dropdownList2: "Admin2",
    dropdownList3: "Admin3",
    icon: "inline-block",
  },
  {
    id: 2,
    list: "Employee",
    iconImg: "images/employee.png",
    dropdownList:"block",
    dropdownList1: "Employee1",
    dropdownList2: "Employee2",
    dropdownList3: "Employee3",
    icon: "inline-block",
  },
  {
    id: 3,
    list: "Customer Support",
    iconImg: "images/Customer Support.png",
    dropdownList:"block",
    dropdownList1: "Support1",
    dropdownList2: "Support2",
    dropdownList3: "Support3",
    icon: "inline-block",
  },
  {
    id: 4,
    list: "Report",
    iconImg: "images/Report.png",
    dropdownList:"block",
    dropdownList1: "Report1",
    dropdownList2: "Report2",
    dropdownList3: "Report3",
    icon: "inline-block",
  },
  {
    id: 5,
    list: "Organization",
    iconImg: "images/Organization.png",
    dropdownList:"block",
    dropdownList1: "Organization1",
    dropdownList2: "Organization2",
    dropdownList3: "Organization3",
    icon: "inline-block",
  },
  {
    id: 6,
    list: "Leave Note",
    iconImg: "images/Leave Note.png",
    dropdownList:"none",
    icon: "none",
  },
  {
    id: 7,
    list: "Projects",
    iconImg: "images/Projects.png",
    dropdownList:"none",
    icon: "none",
  },
  {
    id: 8,
    list: "Settings",
    iconImg: "images/Settings.png",
    dropdownList:"block",
    dropdownList1: "Settings1",
    dropdownList2: "Settings2",
    dropdownList3: "Settings3",
    icon: "inline-block",
  },
];

export default sidePanelList;
